FROM python:3.12-slim
WORKDIR /app

# Install dependencies
COPY pyproject.toml uv.lock ./
RUN pip install uv && uv sync --frozen --group dev

# Copy source code
COPY . .

CMD ["uv", "run", "alembic", "upgrade", "head"]
